import type { NextPage } from 'next'
import {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface IPost {
  firstname?: string
  lastname?: string
  email?: string
}

const Home: NextPage = () => {
  const encode = (data: any) => {
    return Object.keys(data)
        .map(key => encodeURIComponent(key) + "=" + encodeURIComponent(data[key]))
        .join("&");
  };

  const [state, setState] = useState<IPost>();
  const [submitted, setSubmitted] = useState(false);

  const registerUser = (event: React.FormEvent<HTMLFormElement>) => {

    fetch("/", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: encode({ "form-name": "contact", ...state })
    })
      .then(() => console.log("Success!"))
      .catch(error => console.log(error));

    event.preventDefault();
    setSubmitted(true);
  }

  const handleChange = (e: React.FormEvent<HTMLInputElement>) => {
    setState({
      ...state,
      [e.currentTarget.id]: e.currentTarget.value,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
            { (!submitted) && <form name="contact" method="POST" data-netlify="true" onSubmit={registerUser}>
            <input type="hidden" name="form-name" value="contact" />
            <div className="flex gap-4 mb-2">
              <div className="relative">
              <input type="text" id="firstname" className=" rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-jama-accent2 focus:border-transparent" name="firstname" placeholder="First Name"
              onChange={handleChange} />
              </div>
              <div className="relative">
              <input type="text" id="lastname" className=" rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-jama-accent2 focus:border-transparent" name="lastname" placeholder="Last Name"
              onChange={handleChange} />
              </div>
            </div>
            <div className="flex flex-col mb-2">
              <div className=" relative ">
                  <input type="text" name="email" id="email" className=" rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-jama-accent2 focus:border-transparent" placeholder="Email"
                  onChange={handleChange} />
                </div>
            </div>
            <div className="flex w-full my-4">
              <button type="submit" className="py-2 px-4  bg-jama-accent1 hover:bg-jama-accent2 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-lg ">
                  Get Access
              </button>
            </div>
          </form>}
          { submitted && 
            <h5>Thanks for submitting! We&apos;ll reach out ASAP!</h5>
          }
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
